In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sample-dna-sequence/sequences.txt

In [7]:
df = pd.read_csv("/kaggle/input/sample-dna-sequence/sequences.txt")

In [8]:
df.head()

  CCGAGGGCTATGGTTTGGAAGTTAGAACCCTGGGGCTTCTCGCGGACACC
0  GAGTTTATATGGCGCGAGCCTAGTGGTTTTTGTACTTGTTTGTCGC...
1  GATCAGTAGGGAAACAAACAGAGGGCCCAGCCACATCTAGCAGGTA...
2  GTCCACGACCGAACTCCCACCTTGACCGCAGAGGTACCACCAGAGC...
3  GGCGACCGAACTCCAACTAGAACCTGCATAACTGGCCTGGGAGATA...
4  AGACATTGTCAGAACTTAGTGTGCGCCGCACTGAGCGACCGAACTC...

In [9]:
# Python code to transcribe DNA sequence to RNA sequence

# Function to transcribe DNA to RNA
def transcribe_dna_to_rna(dna_sequence):
    # Replace 'T' with 'U' to transcribe DNA to RNA
    rna_sequence = dna_sequence.replace('T', 'U')
    return rna_sequence

# Example DNA sequence
dna_sequence = df.head(0)

# Transcribe DNA to RNA
rna_sequence = transcribe_dna_to_rna(dna_sequence)

# Print the RNA sequence
print("RNA Sequence:", rna_sequence)

RNA Sequence: Empty DataFrame
Columns: [CCGAGGGCTATGGTTTGGAAGTTAGAACCCTGGGGCTTCTCGCGGACACC]
Index: []